### ISSUE TITLE
Making race changes available for race restricted classes.

### ISSUE THREAD

**Issue by Xtortion** [TeraProxy/Surgeon#1]
**Making race changes available for race restricted classes.**

Hiya, I was wondering if this was actually a possibility?

Where for example as a Reaper/Ninja/Gunner/Brawler be able to race change with this module to a different race.

So for example lets say a Gunner that'll be able to race change to a Elin with this module.

And that it'll create this effect:

https://www.youtube.com/watch?v=Et2AhUN02GM

Basically a Elin Gunner with the Castanic combat animations.

Now when you race change for example with any classes mentioned above to any other race that is not actually available for the class, the game crashes.

Is there any possibility to work around this and make this work?

_Also to mention, the game tends to crash most of the time as well when doing a race change even with normal classes_

Thanks in advance already.

**Comment by TeraProxy** [comment]
Unfortunately, that is not possible. At least not to my knowledge. The only possibility to do that is to switch models around in the game files. When doing it with the proxy, it would just crash the game.
Need to look into the crashing some more. Didn't happen to me that much when I released it, hmmm...
